<PoolLine@Label>:
    font_size: '12sp'


GridLayout:
    rows: 5
    size_hint: .2, .15

    line1: line1
    line2: line2
    line3: line3
    line4: line4
    line5: line5

    PoolLine:
        id: line1
        text: '--'

    PoolLine:
        id: line2
        text: '--'

    PoolLine:
        id: line3
        text: '--'

    PoolLine:
        id: line4
        text: '--'

    PoolLine:
        id: line5
        text: '--'
        font_size: '25sp'
